analytics: {}
color:
  brandColors:
    - '#D8D0B0'
    - '#786020'
    - '#B0A068'
    - '#E0C868'
    - '#F8F8E0'
  brandStrength: 0.75
  lightness: 0.8125
  rhythmicContrast: 0.25
  saturation: 0.75
cta: {}
layout_spectrum: 0.1185532642994076
name: muratotti
opengraph: {}
purpose: []
typography_spectrum: 0.41853962768800557
